### ISSUE TITLE
No default styles

### ISSUE THREAD

**Issue by hsingh23** [bsidelinger912/react-tooltip-lite#1]
Could you please include some default styles - like the ones you use in your example

**Comment by bsidelinger912** [comment]
Hello @hsingh23, I'd be happy to look into this.  I'll keep you posted on progress.

**Comment by bsidelinger912** [comment]
Ok @hsingh23, I've finally gotten around to this.  I created a new prop called "useDefaultStyles" which will style the tooltip with .js.  I also updated the docs to explain a bit better how to do it with css and created a codepen demo.  Let me know when you get a chance to try it out.

**Comment by hsingh23** [comment]
I'm on vacation. Will be back in 1 week

**Comment by bsidelinger912** [comment]
Cool, have fun!

**Comment by bsidelinger912** [comment]
Closing this now as I believe I've resolved the original issue.
