### ISSUE TITLE
Tooltip disappears when moving mouse from trigger element to tooltip

### ISSUE THREAD

**Issue by oyeanuj** [bsidelinger912/react-tooltip-lite#11]
Hi @bsidelinger912 , apologies if this has already been asked or answered (couldn't find it anywhere) - how do I ensure that when on hover, I trigger the tooltip, I can move from the triggering element to the tooltip without the tooltip disappearing?

You can see this in action in the examples where it is impossible to hover over the tooltips or select something there - it disappears as soon as the mouse is moved away from the triggering element..

**Comment by bsidelinger912** [comment]
Hey @oyeanuj this was a missing feature and I could think of a lot of relevant use cases.  So I just made an update to add a new "tipContentHover" prop which takes a boolean.  Passing "true" to that prop will give the effect you need.  This is available as of version 1.5.0.  Let me know how it works for you!

**Comment by bsidelinger912** [comment]
Closing as this is resolved with: https://github.com/bsidelinger912/react-tooltip-lite/pull/12
