### ISSUE TITLE
Typescript error: 'Tooltip' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by hallee9000** [bsidelinger912/react-tooltip-lite#128]
I got this error:

```
'Tooltip' cannot be used as a JSX component.
  Its instance type 'Tooltip' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/Users/leadream/figma/heron-transfer-plugin/node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.ts(2786)
```

My dependencies:
```
"react": "16.8.0",
"react-dom": "16.8.0",
"typescript": "^4.6.3",
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "outDir": "dist",
    "jsx": "react",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "noImplicitAny": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
  },
  "include": ["src/**/*", "react-tooltip-lite/dist/index.d.ts", "typings.d.ts", "node_modules/@types/**/*", "node_modules/@figma/**/*"]
}
```

Any solutions?

**Comment by magnattic** [comment]
This usually happens when you have multiple incompatible versions of `@types/react` or `@types/react-dom` installed.
You could use yarn resolutions or npm overrides to force a certain version across all your deps.

**Comment by hallee9000** [comment]
> This usually happens when you have multiple incompatible versions of `@types/react` or `@types/react-dom` installed. You could use yarn resolutions or npm overrides to force a certain version across all your deps.

Thanks @magnattic . Add this in `package.json` solved it.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/12868055/165305369-a53ce77b-796a-4d82-ae70-6425e14a26b7.png">
