### ISSUE TITLE
eventToggle = 'onClick' unwanted behavior on React 16+

### ISSUE THREAD

**Issue by luisbooth7** [bsidelinger912/react-tooltip-lite#17]
Using eventToggle = 'onClick' does work when toggling the tooltip on and off, but clicking anywhere inside the tooltip will toggle the tooltip off when using React 16+. I tried with React 15 and it worked great.

**Comment by luisbooth7** [comment]
You can replicate the issue here [https://codepen.io/anon/pen/oPwyEE](url).

**Comment by bsidelinger912** [comment]
Hey @luisbooth7 Thanks for the codepen, that helps a lot.  I'll look at this over the weekend.

**Comment by bsidelinger912** [comment]
This is resolved with v1.7.1.
