### ISSUE TITLE
Distance prop not working on arrow.

### ISSUE THREAD

**Issue by luisbooth7** [bsidelinger912/react-tooltip-lite#18]
I noticed an unwanted behavior when using the `distance` prop, in which the distance prop will work for adding space from the target to the tooltip container but the arrow doesn't get affected by this. Here's an example.

<img width="403" alt="screen shot 2018-09-10 at 10 54 55 am" src="https://user-images.githubusercontent.com/20545599/45312094-671a7680-b4e8-11e8-91aa-bba2f3134dee.png">

**Comment by bsidelinger912** [comment]
This is resolved with v1.7.1.
