### ISSUE TITLE
Close on click outside the tooltip

### ISSUE THREAD

**Issue by crudh** [bsidelinger912/react-tooltip-lite#24]
Thanks for the great library. We are using it more and more but there is one thing we would like to do: 

Trigger the tooltip with a click on a button (uncontrolled) and then closing the tooltip by clicking anywhere outside of the tooltip.

I couldn't achieve it with the current API at least. Anything you think is worth adding?

**Comment by bsidelinger912** [comment]
Hey guys, this was pretty easy to implement with the existing API by using a fully controlled tooltip, via the "isOpen" prop.  I've updated my example here: https://codepen.io/bsidelinger912/pen/WOdPNK with a click handler on the document that makes a state change to flow a new value for the "isOpen" prop.  You can see the full example at the bottom of that pen.

The handler and the function it calls are like so: 
```
  componentDidMount() {
    document.addEventListener('mousedown', this.bodyClick);
  }

  componentWillUnmount() {
    document.removeEventListener('mousedown', this.bodyClick);
  }

  bodyClick(e) {
    if (this.tipContentRef.contains(e.target)) {
      return;
    }

    this.setState({ tipOpen: false });
  }
```
"this.tipContentRef" is a ref set around the contents of the tooltip like so:
```
<Tooltip
  content={
    <div ref={(el) => { this.tipContentRef = el; }} className="controlled-example">
      <div className="controlled-example_header">
        Hello
        <span className="controlled-example_close-button" onClick={this.toggleTip}>&times;</span>
      </div>
      This tip is controlled by the button, you can also click outside the tip or on the "x" to close it
    </div>
  }
  isOpen={tipOpen}
  tagName="span"
  direction="down"
>
  click the button
</Tooltip>
```

It would be possible to bake something like this into the component with a "closeOnBodyClick" (or something like that) prop, however you'd likely also want to have some way to close the tip from within the tip contents, such as the "x" I used in my example and at that point you really need a fully controlled example anyway.  So for now it seems like just documenting how to implement yourself will probably cover more use cases and avoids adding more surface area to the component's API.  I'd be open to other proposals, but would want to take other likely use cases (such as the one in my example) into account.

**Comment by crudh** [comment]
@bsidelinger912 thanks, seems to work good! I'll test it out some more. Closing this then.
