### ISSUE TITLE
Prop-types warning

### ISSUE THREAD

**Issue by blixtgord** [bsidelinger912/react-tooltip-lite#3]
Portal.jsx should import the prop-types package.

**Comment by bsidelinger912** [comment]
Yes, absolutely, I've been meaning to do this and will handle right away.

**Comment by bsidelinger912** [comment]
Ok, this is fixed in this release: https://github.com/bsidelinger912/react-tooltip-lite/releases/tag/v1.2.1.

**Comment by blixtgord** [comment]
Thank you!
