### ISSUE TITLE
How can I have the tooltip to automatically resize and reposition to new content?

### ISSUE THREAD

**Issue by fmaiabatista** [bsidelinger912/react-tooltip-lite#38]
Hi, I'm using the package to show error tooltips for users in a form being controlled by redux-forms. The problem I'm having is that when my error message changes as the user is typing the input, the tooltip doesn't resize nor reposition itself to match the new message's content.

My case:
![image](https://user-images.githubusercontent.com/1574224/54383079-096e0f00-4670-11e9-8aa0-74f8321340f4.png)
![image](https://user-images.githubusercontent.com/1574224/54383112-1db20c00-4670-11e9-98af-699b44d01b99.png)

I managed to get close to a solution by forcing `width: auto!important; margin: auto!important` (margin is for repositioning) on the `react-tooltip-lite` element.

Result:
![image](https://user-images.githubusercontent.com/1574224/54383929-e6445f00-4671-11e9-9747-d674885967ed.png)
![image](https://user-images.githubusercontent.com/1574224/54383971-fb20f280-4671-11e9-8280-8e8b5eedf4cc.png)
![image](https://user-images.githubusercontent.com/1574224/54383996-0a07a500-4672-11e9-8590-c2e80554ea61.png)

Notice that when going from the 1st error message to the 2nd, `width` works as expected but `margin` doesn't. It will only have effect after the second character is inserted, making the tip to repaint twice before presenting itself correctly.

Is there a a better way to do it?

Thanks!

**Comment by bsidelinger912** [comment]
Hi @fmaiabatista, this is an interesting new use case.  I'm excited to see what you've done with it, this is the type of flexibility I was really hoping react-tooltip-lite would have.  Basically I think we just need to re-run all the calculations when the tooltip contents change.  I haven't run into a situation where the contents where this dynamic while the tooltip was open.  I don't think this will be a difficult change, so I can work on this pretty soon.  Thanks for using my tooltip!

**Comment by easga** [comment]
one of the cases which i assume could be common is when the button is a toggle. the button toggles between two different tooltips and the width is kept for the initial content.

**Comment by fmaiabatista** [comment]
Hey @bsidelinger912 , I ended up using CSS to accomplish this. Here are the styles:

![image](https://user-images.githubusercontent.com/1574224/55732426-55ec0680-59f2-11e9-91b9-e2acb5ce94cf.png)

This gave me the following desired effect:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1574224/55732986-5f29a300-59f3-11e9-987a-d203c32096fa.gif)

Hope this helps!

**Comment by bsidelinger912** [comment]
My other fix got very complicated when I tried to implement.  I'm going to close this as there's a solution, if another use case arises that's not solved by this feel free to open another issue.

**Comment by lastnigtic** [comment]
same problem here: 
![image](https://user-images.githubusercontent.com/17680884/83966490-0e5e5480-a8ed-11ea-9c75-d476d748da62.png)
How I can rewrite '.react-tooltip-lite' width to 'max-content' without using 'important'?
![image](https://user-images.githubusercontent.com/17680884/83966555-6e54fb00-a8ed-11ea-940e-7dc69f75740f.png)

Great work btw.

**Comment by bsidelinger912** [comment]
@fmaiabatista did you need to use !important for your solution?

**Comment by fmaiabatista** [comment]
Hi @bsidelinger912, it's been a while since I posted this and I can't remember the details exactly. But based on my last comment on this thread I managed to set the width to "max-content" without using !important. Seems I only used it on "top" and "left" properties.

> Hey @bsidelinger912 , I ended up using CSS to accomplish this. Here are the styles:
> 
> ![image](https://user-images.githubusercontent.com/1574224/55732426-55ec0680-59f2-11e9-91b9-e2acb5ce94cf.png)
> 
> This gave me the following desired effect:
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1574224/55732986-5f29a300-59f3-11e9-987a-d203c32096fa.gif)
> 
> Hope this helps!
