### ISSUE TITLE
ContentView

### ISSUE THREAD

**Issue by gjabelAmbitas** [bsidelinger912/react-tooltip-lite#39]
I there some way to have some box where react-tooltip-lite can be shown?

If not this will be pretty nice feature.

Example:
I have box with size 200 & 300, inside box i have button with react-tooltip-lite

So if i hover over or click on the button, react-tooltip-lite will just show inside "box" & not outside (respect box dimensions for showing tooltip only inside box).

Thanks.

**Comment by bsidelinger912** [comment]
Hi @gjabelAmbitas there's no feature like this currently.  You could use an iframe to get this effect, as the tooltip will respect it's surrounding window.  I'm a little unsure of why exactly you'd want this, can you elaborate more about the user experience you're going for?

**Comment by bsidelinger912** [comment]
Closing because as far as I can tell this is not something we'll want to do.
