### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Meeinotl** [bsidelinger912/react-tooltip-lite#47]
I noticed that despite being listed as available under an MIT license on its npm page (https://www.npmjs.com/package/react-tooltip-lite) there is no license file in the repository. I would like to use this library in a commercial project but I can only do so if everything is in order legally.

Would you please add a license file? Or if you prefer I can make a pull request to add it. I just need to know the name of the copyright holder so I can add it to the license file.

Thank you for your time.

**Comment by bsidelinger912** [comment]
Hey @Meeinotl I've added the MIT license it should show up no in v1.9.4

**Comment by Meeinotl** [comment]
Thank you @bsidelinger912 for adding this so quickly.
