### ISSUE TITLE
what am I  missing?

### ISSUE THREAD

**Issue by mobyIsMe** [bsidelinger912/react-tooltip-lite#52]
![image](https://user-images.githubusercontent.com/9191594/60795911-18d51300-a19f-11e9-9f4a-b541c376830e.png)

**Comment by bsidelinger912** [comment]
Hey @mobyIsMe usually you'd use an import to get it like so: `import Tooltip from 'react-tooltip-lite';` Beyond that there's not much I can do to help without seeing how you're consuming it.

**Comment by mobyIsMe** [comment]
the whole page is this:
![image](https://user-images.githubusercontent.com/9191594/60855126-21782880-a235-11e9-8456-678f93b45856.png)
in Project, I import like this:
![image](https://user-images.githubusercontent.com/9191594/60855142-2f2dae00-a235-11e9-9415-42a3f137335b.png)
and use it like this: 
![image](https://user-images.githubusercontent.com/9191594/60855168-45d40500-a235-11e9-98c1-4ad3b2f741bf.png)
the changed files are as followed:
![image](https://user-images.githubusercontent.com/9191594/60855193-5ab09880-a235-11e9-9e19-df36fba4b723.png)

**Comment by bsidelinger912** [comment]
Looks like your editor is telling you that it's not properly installed with npm/yarn.  That's usually what the red underline on the import statement will say when you hover over it.

**Comment by bsidelinger912** [comment]
closing as I don't see any actions to take here.
