### ISSUE TITLE
How to tell whether the tooltip is open in the code.

### ISSUE THREAD

**Issue by yasintz** [bsidelinger912/react-tooltip-lite#56]
Hi @bsidelinger912. I sent [pr](https://github.com/bsidelinger912/react-tooltip-lite/pull/55) for the code. Can you help me see if it's turned on without interfering with the ToolTip's operation. I don't want to use "isOpen". I think we can do this in a simpler way.

https://github.com/bsidelinger912/react-tooltip-lite/pull/55

**Comment by crobinson42** [comment]
I would vote for having the `content` prop accept a function, ie:

```
<Tooltip content={({ close, isOpen }) => (...)}>
  ...
</Tooltip>
```

**Comment by bsidelinger912** [comment]
Hey guys, I've been away for a couple weeks on my honeymoon and am just getting back to this stuff.  I'll be thinking more about this this weekend, thanks for your patience.

**Comment by bsidelinger912** [comment]
Pr is merged and released.
