### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by maeligg** [bsidelinger912/react-tooltip-lite#63]
I'm using the latest stable version of react-tooltip-lite, 1.10.0.
When I build my packages for production I get the following warning : 
> (!) Circular dependency: node_modules/react-tooltip-lite/dist/position.js -> node_modules/react-tooltip-lite/dist/getDirection.js -> node_modules/react-tooltip-lite/dist/position.js

It seems to be handled gracefully by npm but maybe worth looking at ?

**Comment by bsidelinger912** [comment]
Hey @maeligg I'll be looking at this soon as I'm working on a bunch of these issues this week.

**Comment by bsidelinger912** [comment]
@maeligg this should be fixed now in v1.11.2
