### ISSUE TITLE
Required props

### ISSUE THREAD

**Issue by alex-malyita** [bsidelinger912/react-tooltip-lite#71]
Referring to the latest changes https://github.com/bsidelinger912/react-tooltip-lite/commit/c3a515614af08fcb4c12a77b39340ebe5d46d64c
`zIndex` has default value - so it should be optional.
And `onToggle` also could be optional.

**Comment by bsidelinger912** [comment]
yeah, thanks @alex-malyita. I meant to make both of those optional, they came in with PRs that didn't update the type declaration file and I added them too hastily. Fixed with v1.11.1 which I just published.
