### ISSUE TITLE
padding props

### ISSUE THREAD

**Issue by pkodzis** [bsidelinger912/react-tooltip-lite#74]
hi, currently padding prop is fixed to number by prototype. So if I use string like e.g.: '0 22px 0 0' it gives:

"index.js:1437 Warning: Failed prop type: Invalid prop `padding` of type `number` supplied to `Tooltip`, expected `string`."

Tooltip with valid CSS string for padding props (like e.g. '0 22px 0 0') works fine. The only issue is the warning mentioned above. Would it be possible to change padding prototype in further releases so it accepts string as well?

**Comment by bsidelinger912** [comment]
Hi @pkodzis the string you posted does not create a prop types warning for me, which makes sense since the propType is set as string, but passing just a number does.  Support for numbers on the padding prop is added with: v1.11.2.
