### ISSUE TITLE
Controlled Tooltips

### ISSUE THREAD

**Issue by oyeanuj** [bsidelinger912/react-tooltip-lite#8]
Hi @bsidelinger912, thank you for putting it out there! I am wondering if it would be possible to make the tooltip controllable with a prop? 

For example, in a form, when there is an error, I would like a tooltip to pop open.

Thoughts?

**Comment by bsidelinger912** [comment]
Hi @oyeanuj, this totally makes sense.  How about a prop like "isOpen" that just takes a boolean?  I imagine it'd override any of the event handlers, so if it was true or false, that would force the tip open/closed and if it was undefined it'd behave as it does now.  Sound good?

**Comment by oyeanuj** [comment]
@bsidelinger912 Yes, that sounds good - kind of how I was imagining it! :)

**Comment by bsidelinger912** [comment]
Ok @oyeanuj I just released v1.4.0, with the new "isOpen" prop.

**Comment by oyeanuj** [comment]
@bsidelinger912 Thanks, will try it out!
