### ISSUE TITLE
Option to render arrow manually (or finer grained arrow styling)

### ISSUE THREAD

**Issue by osdiab** [bsidelinger912/react-tooltip-lite#81]
The current implementation as the README states relies on border tricks to draw a solid arrow, though a design of my company’s puts a border on the arrow itself, which makes this approach problematic - I’m happy to render the arrow myself as an SVG but the library as is doesn’t have a way to define tip rendering manually - would be nice if that’s an option assuming the library doesn’t want to house that kind of logic natively

**Comment by osdiab** [comment]
In the meantime I plan to work around it by rendering the arrow myself with absolute positioning in the body of the tooltip

**Comment by osdiab** [comment]
hmmm the above workaround strategy only works if tooltip position is forced, which makes me want to have some way to retrieve how the tooltip is being positioned. toying around more

**Comment by bsidelinger912** [comment]
Hey @osdiab I've published a version with your change merged, it's v1.12.0

**Comment by osdiab** [comment]
Great, thanks!

**Comment by bsidelinger912** [comment]
Closing as this is released now.
